version: 0.2
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
    - skaffold build --file-output=image.json
    - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
artifacts:
  files:
    - skaffold.yaml
    - image.json
    - buildspec-staging.yaml
    - buildspec-prod.yaml
    - charts/**/*
