version: 0.2
phases:
  pre_build:
    commands:
      - aws eks update-kubeconfig --name {$CLUSTER}
      - mv $CODEBUILD_SRC_DIR_build_output/image.json .
  build:
    commands:
      - skaffold deploy -a image.json -n ${STAGING_NAMESPACE}
